#!/bin/sh

export JAVA_HOME="/opt/android-studio/jbr"
export ANDROID_HOME="$HOME/Android/Sdk"
export NDK_HOME="$HOME/Android/Sdk/ndk/$(/bin/ls -1 $ANDROID_HOME/ndk)"
export PATH="$PATH:$ANDROID_HOME/emulator"
